[build-system]
requires = ["setuptools>=42", "behave>=1.2.5", "selenium>=4.1.3", 'simple-term-menu>=1.5.0', 'prompt-toolkit>=3.0.29',
    'PySimpleGUI>=4.60.3']
build-backend = "setuptools.build_meta"